// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_dr_detection_fixxxx/data/models/dashboard/dashboard_model.dart';
import 'package:flutter_dr_detection_fixxxx/data/models/detection/detection_model.dart';
import 'package:flutter_dr_detection_fixxxx/data/models/patient/patient_model.dart';
import 'package:flutter_dr_detection_fixxxx/data/models/user/user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ClassificationBreakdownAdapter());
    registerAdapter(DetectionModelAdapter());
    registerAdapter(PatientModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ClassificationBreakdownAdapter());
    registerAdapter(DetectionModelAdapter());
    registerAdapter(PatientModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
